name: Deploy to Cloud Run
run-name: ${{ github.actor }} deploying to Cloud Run 🚀

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: 'read'
  id-token: 'write'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: northamerica-northeast2
  SERVICE_NAME: finance-rag-pikklefish
  IMAGE: northamerica-northeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/rag-chatbot/finance-chatbot:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          project_id: ${{env.PROJECT_ID}}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker northamerica-northeast2-docker.pkg.dev --quiet

      - name: Build Docker image
        run: docker build -t $IMAGE .

      - name: Push Docker image
        run: docker push $IMAGE

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v3
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.IMAGE }}
          env_vars: |
            GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}